// <auto-generated />
using System;
using Lucilvio.Solo.Webills.UserAccount.Infraestructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lucilvio.Solo.Webills.UserAccount.Infraestructure.DataAccess.Migrations
{
    [DbContext(typeof(UserAccountContext))]
    partial class UserAccountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lucilvio.Solo.Webills.UserAccount.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("TermAccepted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users","UserAccount");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f474fb2-f6dc-42cd-ac11-5eba4c2b3cd9"),
                            Login = "admin@mail.com",
                            Name = "Administrator",
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            TermAccepted = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
