name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x        
    - name: Build
      run: dotnet build --configuration Release ./src/lucilvio.solo.Webills/Lucilvio.Solo.Webills.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal "./src/lucilvio.solo.Webills"  
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Azure Login
      uses: Azure/login@v1
      env:
        CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      with:        
        creds: ${{ env.CREDS }}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hml-webills'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
